apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/shahnoorkhalidi/python-hello-world   
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds           
    argocd-image-updater.argoproj.io/git-branch: main                                          
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/shahnoor23/nginx-image-updater.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: python


  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

