apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: python
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: python
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: docker.io/shahnoorkhalidi/image-updater-python:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: default
  labels:
    app: python
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: python
  type: NodePort
